version: "3.9"

services:
  caddy:
    image: caddy:2.4.6
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

  registry:
    image: registry:2.8.1
    volumes:
      - registry_data:/var/lib/registry
    restart: unless-stopped
    environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true

  dockeruccio:
    image: node:17.7.1-alpine
    volumes:
      - ../..:/app
      - node_modules:/app/node_modules
    command: /bin/sh -c "cd /app && npm i && npx vite --force"
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
  registry_data:
  node_modules:
